name: Deploy Complete Growth Accelerator Platform

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask==3.0.3 Flask-SQLAlchemy==3.1.1 Flask-WTF==1.2.1 Flask-Login==0.6.3 psycopg2-binary==2.9.9 gunicorn==21.2.0 python-dotenv==1.0.1 requests==2.32.3 Werkzeug==3.0.3 WTForms==3.1.2
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ga-hwaffmb0eqajfza5'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
    
    - name: Configure Azure App Settings
      run: |
        echo "Deployment completed successfully"
        echo "Growth Accelerator Platform deployed to app.growthaccelerator.nl"
