name: Deploy Growth Accelerator to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v || echo "No tests found, continuing deployment"
    
    - name: Create deployment package
      run: |
        zip -r deployment.zip . -x "*.git*" "tests/*" "*.pyc" "__pycache__/*"
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'GA'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment.zip
    
    - name: Verify deployment
      run: |
        sleep 60
        curl -f https://app.growthaccelerator.nl/health || exit 1
        echo "Deployment verified successfully"