name: Deploy to Azure App Services

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'docker-entrypoint.sh'
      - '.github/workflows/azure-deploy.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-identity azure-mgmt-resource azure-mgmt-web azure-mgmt-rdbms
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Deploy to Azure App Services
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          WORKABLE_API_KEY: ${{ secrets.WORKABLE_API_KEY }}
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          SQUARESPACE_API_KEY: ${{ secrets.SQUARESPACE_API_KEY }}
        run: |
          # Run the deploy script with the built image
          python deploy_to_app_services.py \
            --tenant-id "$AZURE_TENANT_ID" \
            --client-id "$AZURE_CLIENT_ID" \
            --client-secret "$AZURE_CLIENT_SECRET" \
            --subscription-id "$AZURE_SUBSCRIPTION_ID" \
            --resource-group "growth-accelerator-rg" \
            --location "westeurope" \
            --app-name "growth-accelerator" \
            --domain "app.growthaccelerator.nl" \
            --docker-image "ghcr.io/${{ github.repository }}:${{ github.sha }}" \
            --env-vars "WORKABLE_API_KEY=$WORKABLE_API_KEY" "LINKEDIN_CLIENT_ID=$LINKEDIN_CLIENT_ID" "LINKEDIN_CLIENT_SECRET=$LINKEDIN_CLIENT_SECRET" "SQUARESPACE_API_KEY=$SQUARESPACE_API_KEY"
      
      - name: Verify deployment
        run: |
          # Wait a bit for the app to start
          echo "Waiting for app to start..."
          sleep 60
          
          # Try to access the app
          curl -sSf https://app.growthaccelerator.nl/health || echo "App not yet available, may still be starting up."