name: Force Flask Deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  force-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Flask app
      run: |
        cat > app.py << 'EOF'
from flask import Flask
app = Flask(__name__)

@app.route('/')
def home():
    return """<!DOCTYPE html>
<html><head><title>Growth Accelerator Platform</title></head>
<body>
<h1>Growth Accelerator Staffing Platform</h1>
<h2>Flask Successfully Deployed to Azure</h2>
<p>Deployment pipeline working: Replit to GitHub to Azure</p>
</body></html>"""

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
EOF
        echo "Flask==3.0.0" > requirements.txt
        echo "gunicorn==21.2.0" >> requirements.txt
    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: GA
        publish-profile: ${{ secrets.AZURE_PUBLISH_PASSWORD }}
        package: .
