name: Growth Accelerator - Synchronized Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: GA
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask==3.0.0 gunicorn==21.2.0 requests==2.31.0 python-dotenv==1.0.0
    
    - name: Create production requirements
      run: |
        cat > requirements.txt << 'EOF'
Flask==3.0.0
gunicorn==21.2.0
requests==2.31.0
python-dotenv==1.0.0
Werkzeug==3.0.1
EOF
    
    - name: Create web.config for Azure
      run: |
        cat > web.config << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="PythonHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="python" 
                  arguments="-m gunicorn app:app --bind 0.0.0.0:%HTTP_PLATFORM_PORT% --workers 2 --timeout 120" 
                  stdoutLogEnabled="true" 
                  stdoutLogFile="\?\%home%\LogFiles\python.log"
                  startupTimeLimit="60" 
                  requestTimeout="00:04:00">
      <environmentVariables>
        <environmentVariable name="PORT" value="%HTTP_PLATFORM_PORT%" />
        <environmentVariable name="PYTHONPATH" value="%home%\site\wwwroot" />
        <environmentVariable name="WORKABLE_API_KEY" value="%WORKABLE_API_KEY%" />
        <environmentVariable name="WORKABLE_SUBDOMAIN" value="growthacceleratorstaffing" />
        <environmentVariable name="DATABASE_URL" value="%DATABASE_URL%" />
        <environmentVariable name="SESSION_SECRET" value="%SESSION_SECRET%" />
        <environmentVariable name="LINKEDIN_CLIENT_ID" value="%LINKEDIN_CLIENT_ID%" />
        <environmentVariable name="LINKEDIN_CLIENT_SECRET" value="%LINKEDIN_CLIENT_SECRET%" />
      </environmentVariables>
    </httpPlatform>
  </system.webServer>
</configuration>
EOF
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: .
        startup-command: 'gunicorn app:app --bind 0.0.0.0:8000 --workers 2'
      env:
        WORKABLE_API_KEY: ${{ secrets.WORKABLE_API_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
        LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
    
    - name: Configure Azure App Settings
      run: |
        az webapp config appsettings set --resource-group GA-group --name ${{ env.AZURE_WEBAPP_NAME }} --settings           WORKABLE_API_KEY="${{ secrets.WORKABLE_API_KEY }}"           WORKABLE_SUBDOMAIN="growthacceleratorstaffing"           DATABASE_URL="${{ secrets.DATABASE_URL }}"           SESSION_SECRET="${{ secrets.SESSION_SECRET }}"           LINKEDIN_CLIENT_ID="${{ secrets.LINKEDIN_CLIENT_ID }}"           LINKEDIN_CLIENT_SECRET="${{ secrets.LINKEDIN_CLIENT_SECRET }}"
